# Generated by Django 3.1.5 on 2021-01-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ornek_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Ornek Model',
                'verbose_name_plural': 'Ornek Modeller',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
    ]
